project:
  type: book
  output-dir: docs

book:
  title: "Hands-on DGGS and OGC DGGS-API with DGGRID and pydggsapi Workshop"
  author: "Alexander Kmoch, Wai Tik Chan, Iris Luik, Kajetan Marcin Chrapkiewicz, Evelyn Uuemaa"
  description: "This hands-on workshop walks through a full DGGS data pipeline. You'll use the FOSS tool DGGRID to index geospatial data and then publish it using pydggsapi, a new open-source server for the OGC API DGGS standard. Leave with a running web service on your laptop."
  license: "CC BY 4.0"
  date: "11/12/2025"
  sidebar:
    logo: files/TYGI_b_logo_transp.png
    search: true
  chapters:
    - index.qmd
    - part: "DGGS Concepts & Introduction"
      chapters:
        - 01_terminology.qmd
        - 02_dggs_grids.qmd
        # - workshop/workshop.qmd
    - part: "Python Setup for the workshop"
      chapters:
        - pysetup/03a_Installing_Micromamba.qmd
        - pysetup/03c_Alternative_Miniconda.qmd
        - pysetup/03d_experimental_pixi.qmd
        - pysetup/04a_Creating_environments.qmd
        - pysetup/04b_alt_install_miniconda.qmd
        - pysetup/05_setup_jupyter.qmd
    - part: "DGGRID and dggrid4py"
      chapters:
        - dggrid/dggrid_intro.qmd
        - data_conversion/data_conversion.qmd
        # - dggrid_advanced/dggrid_advanced.qmd
    
    - part: "Pydggsapi and OGC API - DGGS"
      chapters:
        - pydggsapi/pydggsapi_intro.qmd
        # - pydggsapi_advanced/pydggsapi_advanced.qmd
    - references/license.qmd
    - references/references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
    toc-title: "On this page"
    number-sections: false
    code-overflow: scroll
    toc-depth: 2
jupyter: python3

